version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "automerge"
    ignore:
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "team-extension-maintainers"

  - package-ecosystem: "npm"
    directory: "/agent"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "automerge"
      - "agent"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "team-agent-maintainers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automerge"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "team-devops"