changelog:
  exclude:
    labels:
      - "skip-changelog"
      - "duplicate"
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🔧 Maintenance"
      labels:
        - "chore"
        - "documentation"
        - "dependencies"
    - title: "💡 Agent Updates"
      labels:
        - "agent"
    - title: "📝 Other Changes"
      labels:
        - "*"