version: '3.8'

services:
  app:
    image: node:slim
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sleep infinity
    working_dir: /app
    ports:
      - "3000:3000"
