name: Artifacts Management Workflow

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Name of the artifact to manage'
        required: true
        default: 'build-artifact'
      artifactPath:
        description: 'Path to files for uploading'
        required: true
        default: './dist'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.artifactName }}
          path: ${{ github.event.inputs.artifactPath }}
          retention-days: 5

  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.artifactName }}
          path: './downloaded-artifacts'

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la ./downloaded-artifacts
