name: Build and Push Dev Container

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/build-push-devcontainer.yml'
  schedule:
    - cron: '0 0 * * 0' # Weekly build on Sundays
  workflow_dispatch: # Manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: '--allow-insecure-entitlement network.host'
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY || 'docker.io' }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/cloudbuild
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch,prefix=build-
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cloudbuild:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cloudbuild:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            USER_UID=1000
            USER_GID=1000
