name: Scheduled Integration

# Required secrets:
# - SLACK_WEBHOOK: Webhook URL for Slack notifications

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:integration

      - name: Generate integration test report
        if: always()
        run: npm run generate-test-report

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: |
            test-reports/
            coverage/

      - name: Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "danger"
          SLACK_TITLE: "Integration Test Failure"
          SLACK_MESSAGE: "Daily integration tests have failed. Check the GitHub Actions log for details."
