name: Reusable Upload Artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to upload'
        required: true
        type: string
      artifact-path:
        description: 'Path to files to upload'
        required: true
        type: string
      retention-days:
        description: 'Number of days to retain the artifact'
        required: false
        default: 90
        type: number

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: ${{ inputs.retention-days }}
