name: VS Code Insiders CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup VS Code Insiders
        run: |
          npm install -g @vscode/vsce
          npm install -g @vscode/test-electron

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build extension
        run: npm run compile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Package extension
        run: vsce package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-package-${{ matrix.os }}
          path: "*.vsix"
